#!/usr/bin/env python3
"""
bitmap_convert.py — Convert PNG images to GDEM102F91 PROGMEM bitmap arrays.

Supports two output formats:
  2bpp  — 4-color (black/white/yellow/red), 4 pixels per byte, MSB-first.
          Use with drawBitmap2bpp(). Width must be a multiple of 4.
  1bpp  — monochrome, 8 pixels per byte, MSB = leftmost pixel.
          Use with drawBitmap1bpp(). Any width accepted.

The display's 4-color palette:
  black  = (0,   0,   0)
  white  = (255, 255, 255)
  yellow = (255, 215, 0)
  red    = (255, 0,   0)

Usage:
  python3 bitmap_convert.py --mode 2bpp logo.png
  python3 bitmap_convert.py --mode 1bpp --threshold 128 icon.png
  python3 bitmap_convert.py --mode 2bpp --name myLogo --output logo.h logo.png

Requirements:
  pip install Pillow
"""

import argparse
import math
import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

# ─── Display palette ──────────────────────────────────────────────────────────
PALETTE = {
    "black":  (0,   0,   0),
    "white":  (255, 255, 255),
    "yellow": (255, 215, 0),
    "red":    (255, 0,   0),
}
# 2bpp encoding: black=0, white=1, yellow=2, red=3
PALETTE_2BPP = {
    "black":  0,
    "white":  1,
    "yellow": 2,
    "red":    3,
}


def nearest_palette_color(r, g, b):
    """Return the 2bpp index of the nearest palette entry."""
    best_name, best_dist = None, float("inf")
    for name, (pr, pg, pb) in PALETTE.items():
        d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if d < best_dist:
            best_dist, best_name = d, name
    return PALETTE_2BPP[best_name]


def convert_2bpp(img, var_name):
    """
    Convert an RGBA/RGB image to a 2bpp PROGMEM byte array.
    Width is padded to the next multiple of 4.
    """
    img = img.convert("RGBA")
    w, h = img.size

    # Pad width to multiple of 4
    padded_w = math.ceil(w / 4) * 4
    if padded_w != w:
        print(f"  Note: width {w} padded to {padded_w} (must be multiple of 4 for 2bpp)")
    row_bytes = padded_w // 4

    pixels = img.load()
    data = []

    for y in range(h):
        for byte_idx in range(row_bytes):
            packed = 0
            for bit in range(4):           # 4 pixels per byte
                px = byte_idx * 4 + bit
                if px < w:
                    r, g, b, a = pixels[px, y]
                    if a < 128:            # transparent → white background
                        color_idx = PALETTE_2BPP["white"]
                    else:
                        color_idx = nearest_palette_color(r, g, b)
                else:
                    color_idx = PALETTE_2BPP["white"]  # padding → white
                packed = (packed << 2) | (color_idx & 0x03)
            data.append(packed)

    return _format_output(var_name, padded_w, h, "2bpp", row_bytes, data)


def convert_1bpp(img, var_name, threshold):
    """
    Convert an RGBA/RGB image to a 1bpp PROGMEM byte array.
    Pixels brighter than threshold → 0 (background/clear bit).
    Pixels at/below threshold → 1 (foreground/set bit).
    """
    img = img.convert("RGBA")
    w, h = img.size
    row_bytes = math.ceil(w / 8)

    pixels = img.load()
    data = []

    for y in range(h):
        for byte_idx in range(row_bytes):
            packed = 0
            for bit in range(8):
                px = byte_idx * 8 + bit
                if px < w:
                    r, g, b, a = pixels[px, y]
                    if a < 128:
                        luma = 255       # transparent → background
                    else:
                        luma = int(0.299 * r + 0.587 * g + 0.114 * b)
                    set_bit = 1 if luma <= threshold else 0
                else:
                    set_bit = 0          # padding
                packed = (packed << 1) | set_bit
            data.append(packed)

    return _format_output(var_name, w, h, "1bpp", row_bytes, data)


def _format_output(var_name, w, h, mode, row_bytes, data):
    total = len(data)
    lines = [
        f"// {var_name} — {w}×{h} px, {mode}, {row_bytes} bytes/row, {total} bytes total",
        f"// Generated by bitmap_convert.py",
        f"// Usage: display.drawBitmap{mode.replace('b','B',1)}(x, y, {w}, {h}, {var_name});",
        f"",
        f"static const uint8_t {var_name}[] PROGMEM = {{",
    ]

    # 16 bytes per output line for readability
    for i in range(0, total, 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hex_vals},")

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert PNG to GDEM102F91 PROGMEM bitmap array"
    )
    parser.add_argument("input", help="Input PNG file")
    parser.add_argument(
        "--mode", choices=["1bpp", "2bpp"], default="2bpp",
        help="Output bit depth (default: 2bpp)"
    )
    parser.add_argument(
        "--name", default=None,
        help="C variable name (default: filename without extension)"
    )
    parser.add_argument(
        "--output", default=None,
        help="Output .h file (default: <input_name>_<mode>.h)"
    )
    parser.add_argument(
        "--threshold", type=int, default=128,
        help="1bpp luminance threshold 0-255 (default: 128)"
    )
    parser.add_argument(
        "--resize", default=None,
        help="Resize image before converting, e.g. --resize 64x64"
    )
    args = parser.parse_args()

    src = Path(args.input)
    if not src.exists():
        sys.exit(f"File not found: {src}")

    var_name = args.name or src.stem.replace("-", "_").replace(" ", "_")
    out_path = Path(args.output) if args.output else src.with_name(f"{src.stem}_{args.mode}.h")

    img = Image.open(src)

    if args.resize:
        try:
            rw, rh = (int(v) for v in args.resize.lower().split("x"))
            img = img.resize((rw, rh), Image.LANCZOS)
            print(f"  Resized to {rw}×{rh}")
        except ValueError:
            sys.exit("--resize must be WxH, e.g. 64x64")

    w, h = img.size
    print(f"Converting '{src.name}' ({w}×{h}) → {args.mode} → '{out_path.name}'")

    if args.mode == "2bpp":
        output = convert_2bpp(img, var_name)
    else:
        output = convert_1bpp(img, var_name, args.threshold)

    out_path.write_text(output, encoding="utf-8")
    print(f"  Written to {out_path}")
    print(f"  Include in your sketch: #include \"{out_path.name}\"")


if __name__ == "__main__":
    main()
